### PR TITLE
64 bit support

### PR DESCRIPTION
**Pull request by frederich**
Hello,

my name is Jens. I've added 64-bit support and removed all warnings.

Best regards,
Jens

### CODE REVIEW

**Comment by derekmcloughlin** [comment]
Cool. I didn't even know there was a 64-bit version of Vim on Windows. Thanks!

**Comment by frederich** [comment]
Hello Derek,

no problem :-). You can grab a 64-bit vim copy from google code: http://code.google.com/p/vim-win3264
I will test the changes for a certain time.

**Comment by frederich** [comment]
Hell Derek, I've improved the makefile and added a 64-bit compiled dll.

**Comment by alex-shamshurin** [comment]
Hmm, it seems that package is not maintained anymore, but anyway I'd like to have vim in fullscreen under windows

**Comment by derekmcloughlin** [comment]
I'll merge it after lunch.

**Comment by derekmcloughlin** [comment]
@alex-shamshurin can you check that it works?

**Comment by alex-shamshurin** [comment]
Ok, today I'll check it and reply.

**Comment by alex-shamshurin** [comment]
Yes, thank you! It works! I could not compile it with VS2017 - some errors! May be you add some additional description how to complile it... But anyway compiled dll works, it's great!

**Pull request merged**
